[package]

name = "guessing_game_tcp"
version = "0.1.0"
authors = [ "steve@steveklabnik.com", "nick@wabbo.org" ]

[[bin]]

name = "guessing_game_tcp_server"

[[bin]]

name = "guessing_game_tcp_client"

